### ISSUE TITLE
REM not # for in Windows batch script

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/conda-forge-build-setup-feedstock#12]
`#` is not a valid comment indicator in batch files, `REM` should be used instead.

**Comment by jakirkham** [comment]
Ack, sorry, that was a brain fart on my part.

**Comment by jakirkham** [comment]
Actually, I guess I can't take responsibility for those lines as they are not mine, but I can fix them at least.

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/13 ).
