### ISSUE TITLE
Upload script fails with conda_build >= 2.0.0

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/conda-forge-build-setup-feedstock#28]
Copied from conda-forge/conda-smithy#282

conda build version 2.0.0 changed the call signature of the [`bldpkg_path()` function](https://github.com/conda/conda-build/commit/cd2f45ccc4e984dd1b9ec05b71c4ee3317ff4d23) so that it now takes a second `config` argument.  This breaks the `upload_or_check_non_existence.py` script in conda-smithy, see conda-forge/doctr-feedstock#5.

A temporary fix which pins `conda-build` to 1.x was made in #27 but should be reverted once the upload script is updated to account for this new call signature.

**Comment by jjhelmus** [comment]
The following change around line 25 to the [`upload_or_check_non_existence.py` script](https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/upload_or_check_non_existence.py#L25) seems to fix the issue and would allow for compatibility between conda build 1.x and 2.x:

``` Python
try:
     fname = bldpkg_path(meta)
except TypeError:
     # conda-build >= 2.0.0 takes a config argument
     from conda_build.config import Config
     config = Config()
     fname = bldpkg_path(meta, config)
```

I would appreciate hearing what @msarahan or @pelson thinks of this change.

**Comment by msarahan** [comment]
That change would be fine.

**Comment by pelson** [comment]
Yep, I'd merge this.

**Comment by pelson** [comment]
This is now fixed, and conda-smithy is now directing feedstocks at the script in this repo.
