### ISSUE TITLE
Using ~~post-link~~ scripts?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-build-setup-feedstock#3]
We set this up using activate scripts, but honestly I think we would be happier with post-link scripts. This would avoid having to activate afterwards and would take affect immediately after install. It also avoids much of the weirdness associated with activation scripts.

**Comment by jankatins** [comment]
If you use postlink scripts, could you check for `CI` (or even one of the travis/appveyor/circleci specific ones) in the environment variables and error if it is not found? Thats would prevent users installing such a package...

**Comment by jakirkham** [comment]
Absolutely, we should totally do that.

**Comment by pelson** [comment]
I'm half inclined to be explicit and just have a script that the feedstock _runs_...

```
$ conda install conda-forge-build-setup
$ run_conda_forge_build_setup
```

I can also see the advantage of not doing this though...

**Comment by pelson** [comment]
The more I think on it, the more I'd like to avoid making stateful changes in `activate` - it just doesn't seem very friendly. I definitely advocate making the conda-forge config step explicit. To help @janschulz's usecase we should also avoid adding the conda-forge channel in this package, and should maintain that as part of the feedstock itself IMO (the pip stuff etc. is good here).

**Comment by jakirkham** [comment]
I'm sorry I'm not sure I follow that comment. I get that avoiding `activate` is generally a good idea. That certainly should be the case here (if that is what you are trying to say). Having an explicit config script is fine. Doesn't seem more or less friendly than having to use activate, but it is clearer and avoids issues offline. So, on all of this. 👍 

> To help @janschulz's usecase we should also avoid adding the conda-forge channel in this package...

So, I'm starting to lose you here. What use case? Why is adding the conda-forge channel a bad idea. How is this a problem if we have an explicit script that one must execute?

> ...and should maintain that as part of the feedstock itself IMO...

??? Sorry completely lost. 😕 What stuff and what is here? Just the configuration script? If that's the case, I'm on-board, but I'm still thrown by the vagueness of this statement.

> the pip stuff etc. is good here

Which pip stuff? Whether pip is a python dependency? If so, I guess 👍 assuming I understood the previous portion correctly.

Sorry just having a bit of trouble following. I think I may be on-board, but a clearer explanation would definitely help. 😄

**Comment by pelson** [comment]
Sorry @jakirkham. I completely agree with how vague that previous comment was. My apologies. In truth, the source of the misunderstanding is that the comment doesn't properly relate to this issue at all. I'll try to add some detail though.

I was referring to the line [`conda config --add channels conda-forge`](https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/activate.sh#L1). I think adding conda-forge as a channel in this package is best avoided for two reasons:
- we need conda-forge to be on the channels to install conda-forge-build-setup in the first place
- not having it in this package means that others (such as @janschulz) can use the conda-smithy machinery to make useful feedstocks outside of conda-forge

My comment wasn't meant to confuse, and I agree, it was totally ambiguous. Apologies again.

**Comment by jakirkham** [comment]
No worries. It's probably time for me to get some 😴 too. 😉

The point you raise above is totally sensible to me. 👍

**Comment by jakirkham** [comment]
Alright, please take a look at this PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/5 ) when you have time. It's a total rewrite to use scripts.

**Comment by jakirkham** [comment]
Maybe we should talk about including all `conda config` again. See this discussion ( https://github.com/Anaconda-Platform/support/issues/45 ).
