### ISSUE TITLE
Upload script mislabels packages

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-build-setup-feedstock#41]
It seems the upload script will sometimes placing things under the intended label (e.g. `prerelease`) and `main` even when `main` is not specified. It will do this with packages that it is now uploading from a CI build and with old packages it is not rebuilding. This creates havoc when trying to ensure a prerelease or broken package doesn't get pulled in by default.

xref: https://github.com/conda-forge/pysocks-feedstock/pull/1#discussion-diff-89323989R9

cc @pelson

**Comment by jjhelmus** [comment]
The labels of the `python` package on Anaconda.org are [incorrect again](https://anaconda.org/conda-forge/python/files).  I don't have permissions to change these back to the correct labels but would appreciate if someone could fix them.

**Comment by ocefpaf** [comment]
>  I don't have permissions to change these back to the correct labels but would appreciate if someone could fix them.

Doing that now...

---

Edit: done! Can you take a look and see if I got them right?

**Comment by jjhelmus** [comment]
> Edit: done! Can you take a look and see if I got them right?

The packages with the `broken` label need `main` removed but other than that looks good.  Thanks!

**Comment by ocefpaf** [comment]
> The packages with the `broken` label need `main` removed but other than that looks good.  Thanks!

Missed those. Can you check again and give the all clear?

**Comment by jjhelmus** [comment]
Looks good now.  Thanks again.

**Comment by pelson** [comment]
Incidentally, I've just added @jjhelmus to the conda-forge owners group on anaconda.org.

**Comment by jakirkham** [comment]
Alright, I've tried to fix this in PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/65 ), but it may mean the end of an (unused?) feature. Would appreciate feedback on it.

**Comment by jakirkham** [comment]
I guess this is fixed. Though if people see issues, please do report and we can reinvestigate.
