### ISSUE TITLE
ff_ci_pr_build.py fails a PR build when a commit is completely removed from history

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-build-setup-feedstock#66]
I pushed commit "a" and then pushed commit "b". And then realized commit "b" is not needed. Removed commit "b" and force pushed. Restarted travis-ci for commit "a". `ff_ci_pr_build.py` failed the build.

**Comment by jakirkham** [comment]
Thanks @isuruf.

That isn't too surprising actually. The script cancels any build number for a PR except the latest one. This is what the Julia AppVeyor code did before too. Though AppVeyor and CircleCI give you a new build when you restart. Travis CI unfortunately does not. If Travis did give you a new build, then this would fix the issue.

I don't really see a good way to fix this in the script that doesn't have worse side effects. Though if you do, please feel free to suggest one. For now would suggest amending commit `a` and force pushing or pushing a reversion commit `c` after `b`.

**Comment by isuruf** [comment]
Thanks for the info. I ended up amending the commit and force pushing
