### ISSUE TITLE
Circle CI builds incorrectly being marked as outdated

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/conda-forge-build-setup-feedstock#75]
With the move to Circle CI 2.0 workflows and build matrices, conda-forge/conda-smithy#532, the check in `ff_ci_pr_build.py` for the [latest build number](https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/ff_ci_pr_build.py#L67-L72) is no longer a good metric to determine if a build should be skipped since multiple builds are created for each Python version. This leads to the build being marked as outdated and being skipped, for example conda-forge/pyflakes-feedstock#13.  Is there another metric that we can use to determine outdated builds with Circle CI 2.0?

**Comment by jjhelmus** [comment]
@jakirkham You are the conda-forge expert on Circle CI 2.0, any thought on this?

**Comment by jakirkham** [comment]
Hey @jjhelmus, thanks for the report. I'm not sure why I didn't see this issue in testing.

In any event, was able to juggle restarting the CI builds for `pyflakes` to fix this for your PR in question. As for a longer term fix, I think PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/76 ) should do what you want.

There is a minor issue with the default value being ignored by the `get` call. Not entirely sure what is going wrong there, but it only matters for non-CircleCI 2.0 builds.

**Comment by jakirkham** [comment]
Also PR ( https://github.com/conda-forge/conda-build-all-feedstock/pull/35 ) acts as a test of this.
