### ISSUE TITLE
upload_or_check_non_existence fails check on upload noarch packages

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-build-setup-feedstock#80]
Seems that `upload_or_check_non_existence.py` has no issues uploading noarch Python packages. However if a noarch Python package is already uploaded, it seems to fail. Not sure if this is because it fails to identify the package is already upload and tries again or if this is for some other reason. This makes it look like builds are failing on noarch Python feedstocks when that is not the case. Would be good if we could fix the script to better handle noarch Python packages that have already been uploaded. Example of such a failure in a build log linked below.

ref: https://circleci.com/gh/conda-forge/dask-distance-feedstock/2

**Comment by jakirkham** [comment]
cc @isuruf

**Comment by isuruf** [comment]
PR at #81

**Comment by jakirkham** [comment]
Hmm...still seeing issues for this case.

ref: https://circleci.com/gh/conda-forge/dask-distance-feedstock/4
