### ISSUE TITLE
upload script fails with conda-build 3.0

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-build-setup-feedstock#83]
```
$ upload_or_check_non_existence ./recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 126, in <module>
    main()
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 107, in main
    for _, meta in meta_main.get_output_metadata_set(files=None):
TypeError: get_output_metadata_set() got an unexpected keyword argument 'files'
The command "upload_or_check_non_existence ./recipe conda-forge --channel=main" exited with 1.
```

ref: https://travis-ci.org/msarahan/click-feedstock/jobs/308655327#L367-L377

**Comment by msarahan** [comment]
In pretty sure this script will need more work than just fixing that
keyword arg. I'll add **kw to conda build's function so that there won't be
an error any more, but I think we'll need to redefine what it means for
something to already exist, as we discussed in the meeting, where hashes
make this problem harder.

More later today.

**Comment by isuruf** [comment]
@msarahan, what do you have in mind for "redefine what it means for something to already exist"? I can't exactly remember what was discussed at the meeting.

**Comment by jakirkham** [comment]
Assuming I’m understanding correctly, the issue is packages have hashes with cb3. Though the hash may change even though someone didn’t intend to make a release (e.g. no build number or version change). So the general feeling is we don’t want to release in that case. Hence the check for package existence needs to be updated to ignore the hash when checking for matching packages in the channel.

**Comment by jakirkham** [comment]
Solved in `conda-forge-ci-setup`, which will be used with `conda-build` 3 instead of this. So this is a non-issue now solved by other means. Closing.
