### ISSUE TITLE
New package name

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-build-setup-feedstock#92]
I'm thinking of renaming this package and then pinning it to a major version in the conda-smithy generated files. Reason is that this package is not pinned in the feedstocks and it's making it difficult to test. For example, https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/88 was a change that would work with `conda-smithy>=3.0.0`, but not before. Also I can't test `conda-smithy==3.0.0`, without merging #84.

Therefore I propose to take the changes of #84 and create a new package `conda-forge-ci-setup` and have `conda install conda-forge-ci-setup=1.*` in the feedstock templates of `conda-smithy=3.0.0`

cc @conda-forge/core

**Comment by jakirkham** [comment]
SGTM
